"""Publisher download filenames encode the DOI, usually with the
punctuation filed off. Worth trusting: a filename is generated by
the publisher's own download pipeline for *this* file, whereas the
embedded Info dict is whatever template the operator left in it —
`advances-in-direct-methods-…-S0959440X99000202-main.pdf` claims,
in its metadata, to be "List of Referees 1999" with a Process
Safety and Environmental Protection DOI.

Filenames here are real ones from the library.
"""

import os
import sys

HERE = os.path.dirname(os.path.abspath(__file__))
ROOT = os.path.dirname(HERE)
if ROOT not in sys.path:
    sys.path.insert(0, ROOT)

from alexandria.extract import doi_from_filename as dfn


# ---- Elsevier PII --------------------------------------------------

def test_elsevier_pii_with_check_digit():
    assert dfn("1-s2.0-S0022283695800379-molecular-recognition.pdf") \
        == "10.1016/s0022-2836(95)80037-9"


def test_elsevier_pii_with_x_in_the_journal_code():
    assert dfn("advances-in-direct-methods-for-protein-crystallography"
               "-1-s2.0-S0959440X99000202-main.pdf") \
        == "10.1016/s0959-440x(99)00020-2"


def test_elsevier_pii_2000s():
    assert dfn("1-s2.0-S1097276522006608-main.pdf") \
        == "10.1016/s1097-2765(22)00660-8"


def test_elsevier_pii_recent():
    assert dfn("1-s2.0-S0303720726000912-main.pdf") \
        == "10.1016/s0303-7207(26)00091-2"


# ---- other publishers ----------------------------------------------

def test_arxiv_strips_the_version():
    assert dfn("2006.11239v2.pdf") == "10.48550/arxiv.2006.11239"


def test_biorxiv_full_text():
    assert dfn("2024.04.29.591684v1.full.pdf") \
        == "10.1101/2024.04.29.591684"
    assert dfn("2022.03.07.483312.full.pdf") \
        == "10.1101/2022.03.07.483312"


def test_biorxiv_duplicate_suffix_is_ignored():
    assert dfn("2025.11.24.689453.full-1.pdf") \
        == "10.1101/2025.11.24.689453"


def test_nature_bmc():
    assert dfn("s41467-025-56045-z.pdf") == "10.1038/s41467-025-56045-z"


def test_rsc():
    assert dfn("d1ob00658d.pdf") == "10.1039/d1ob00658d"


def test_acs():
    assert dfn("acs.jcim.4c02293.pdf") == "10.1021/acs.jcim.4c02293"


def test_pnas():
    assert dfn("pnas.0502225102.pdf") == "10.1073/pnas.0502225102"


def test_science_and_sciadv():
    assert dfn("science.aef8874.pdf") == "10.1126/science.aef8874"
    assert dfn("sciadv.abg3338.pdf") == "10.1126/sciadv.abg3338"


# ---- what must NOT be decoded --------------------------------------

def test_supplementary_files_are_refused():
    """Decoding gives the *parent* article's DOI — useful, but it
    must not label the supplement as being that paper."""
    for name in ("13321_2020_429_MOESM2_ESM.pdf",
                 "42004_2020_367_MOESM1_ESM.pdf",
                 "jm5c03004_si_001.pdf",
                 "pnas.2524504123.sapp.pdf"):
        assert dfn(name) is None, name


def test_unrecognised_names_return_none():
    for name in ("emsley2004_i_coot_i.pdf", "sigmaa.pdf",
                 "ba5278.pdf", "qe5003.pdf", "", None):
        assert dfn(name) is None, name


def test_full_paths_work_too():
    assert dfn("/home/x/Documents/Alexandria/d1ob00658d.pdf") \
        == "10.1039/d1ob00658d"


if __name__ == "__main__":
    import pytest
    sys.exit(pytest.main([__file__, "-v"]))


def test_springer_bmc_and_nature_are_told_apart():
    """Same sNNNNN shape, three different prefixes — a single
    10.1038 rule mislabelled the Springer ones in the library."""
    assert dfn("s41467-025-56045-z.pdf") == "10.1038/s41467-025-56045-z"
    assert dfn("s13321-023-00786-w.pdf") == "10.1186/s13321-023-00786-w"
    assert dfn("s00775-026-02148-x.pdf") == "10.1007/s00775-026-02148-x"
